config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  resources :posts do
    resources :comments
    resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
   validates :title, presence: true,
                        length: {minimum: 5}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
      redirect_to post_path(@post)
  end

  def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:post_id])
  end

  private def comment_params
      params.require(:comment).permit(:username, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
      @title = 'About Us'
      @content = 'This is the about page'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "hosanna", password: "1234", except: [:index, :show]

  def index
      @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end


  def new
    @post = Post.new
  end

  def create
      #render plain: params[:post].inspect
      @post = Post.new(post_params)
      if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
      @post = Post.find(params[:id ])
  end

  def update
    @post = Post.find(params[:id ])

    if(@post.update(post_params))
    redirect_to @post
  else
    render 'edit'
  end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to_posts_path
  end

  private def post_params

    params.require(:post).permit(:title, :description)

  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
 <div class="well">
   <p><strong><%= comment.username %></strong>: <%= comment.body %>
     <%= link_to "[X]", [comment.post, comment],
     method: :delete,
     data: { confirm: 'Are you sure?'}%>
   </p>
 </div>
 <% end %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>


  <p>
    <%= f.label :username %><br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

<P>
</p>
  <p>

    <!--<%= f.submit({:class => 'btn btn-primary'})%>-->
    <%= f.submit "Comment", class: "btn" %>

  </p>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Manager</title>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag "application" %>

       </head>



  <body>

    <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Task Manager</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to "Home", home_path %></li>

              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Create Projects", new_post_path %></li>

              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>

        <div  class="container">

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1> Edit Project </h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>

<P>
</p>
  <p>

    <!--<%= f.submit({:class => 'btn btn-primary'})%>-->
    <%= f.submit "Update", class: "btn btn-primary" %>


  </p>

  <% end %>

app/views/posts/index.html.erb
<h1>Projects</h1>
<head><title>Task Manager</title></head>

<% @posts.each do |post| %>
<div class="well">
    <h3><%= post.title %></h3>
    <p><%= post.description %></p>
    <%= link_to "Details", post_path(post),  :class  => 'btn btn-default' %>
    <%= link_to "Add Task", post_path(post),  :class  => 'btn btn-default' %>
</div>
<% end %>

app/views/posts/new.html.erb
<h1> Add Project </h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>

<P>
</p>
  <p>

    <!--<%= f.submit({:class => 'btn btn-primary'})%>-->
    <%= f.submit "Add", class: "btn btn-primary" %>

  </p>

  <% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.description %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to 'Delete', post_path(@post),
method: :delete,
data: { confirm: 'Are you sure?'},
 :class => 'btn btn-danger' %>

 <hr>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>